# Generated by Django 4.0.6 on 2022-09-09 19:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
                ('ch', models.CharField(choices=[('3', 'Three'), ('4', 'Four')], max_length=5)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enrollment_start_date', models.DateField()),
                ('enrollment_end_date', models.DateField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.course')),
                ('student', models.ManyToManyField(to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
        ),
    ]
