# Generated by Django 4.0.6 on 2022-09-10 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enrollment_start_date', models.DateField()),
                ('enrollment_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday')], max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_no', models.CharField(choices=[('ROOM_1', 'Room 1'), ('ROOM_2', 'Room 2'), ('ROOM_3', 'Room 3'), ('ROOM_4', 'Room 4'), ('Not Announced Yet', 'Not Announced')], default='Not Announced Yet', max_length=50)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
                ('ch', models.CharField(choices=[('3', 'Three'), ('4', 'Four')], max_length=5)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.course'),
        ),
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(default=None, to='accounts.student'),
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='A', max_length=5)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('student', models.ManyToManyField(default=None, to='accounts.student')),
            ],
        ),
    ]
