# Generated by Django 4.0.3 on 2022-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
