# Generated by Django 4.0.6 on 2022-09-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(default=None, to='accounts.student'),
        ),
    ]
