# Generated by Django 4.0.3 on 2022-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
