# Generated by Django 4.0.6 on 2022-09-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_type'),
        ('classes', '0002_alter_classes_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ManyToManyField(default=None, to='accounts.student'),
        ),
    ]
