# Generated by Django 4.0.3 on 2022-09-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_classes_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_req_courses',
            field=models.ManyToManyField(null=True, to='classes.course'),
        ),
    ]
