# Generated by Django 4.0.3 on 2022-09-24 08:28

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_alter_course_course_code_alter_course_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="name", unique=True
            ),
        ),
    ]
