# Generated by Django 4.0.3 on 2022-09-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_course_pre_req_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_req_level',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=1),
        ),
    ]
