# Generated by Django 4.0.3 on 2022-09-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_course_pre_req_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_req_courses',
            field=models.ManyToManyField(default=None, null=True, to='classes.course'),
        ),
    ]
