# Generated by Django 4.0.3 on 2022-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_classes_slug'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmore',
            name='cleared_course',
            field=models.ManyToManyField(blank=True, to='classes.course'),
        ),
    ]
