# Generated by Django 4.0.3 on 2022-09-29 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentmore_cleared_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherMore',
        ),
    ]
