# Generated by Django 4.0.3 on 2022-10-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentmore_cleared_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermore',
            name='degree',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
