# Generated by Django 4.0.3 on 2022-10-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teachermore_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermore',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teachermore',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
